openapi: 3.0.1
info:
  version: 1.0.0
  title: Article DomainのAPI
  description: Article関連のAPI週
  license:
    name: MIT
externalDocs:
  url: "https://himenon.github.io/openapi-practice/article"
  description: "自動生成ドキュメント"

servers:
  - url: http://localhost:4000
    description: ローカル開発環境
  - url: http://localhost:5000
    description: 本番環境

tags:
- name: Article
  description: "投稿記事の情報"

components:
  schemas:
    Model:
      $ref: "./components/schemas/_Model.yml"
    Created:
      $ref: "./components/schemas/success/CreatedResponse.yml"
    Updated:
      $ref: "./components/schemas/success/UpdatedResponse.yml"
    Deleted:
      $ref: "./components/schemas/success/DeletedResponse.yml"
    FailedCreate:
      $ref: "./components/schemas/failed/CreateResponse.yml"
    FailedUpdate:
      $ref: "./components/schemas/failed/UpdateResponse.yml"
    FailedDelete:
      $ref: "./components/schemas/failed/DeleteResponse.yml"
  parameters:
    ArticleId:
      $ref: ./components/parameters/ArticleId.yml

paths:
  /article/:
    post:
      operationId: create
      description: 記事を作成する
      tags:
        - Article
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Model"
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Created"

  /article/{articleId}:
    get:
      operationId: get
      description: 記事を取得する
      tags:
        - Article
      parameters:
        - $ref: "#/components/parameters/ArticleId"
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Model"
        400:
          description: 異常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailedCreate"

    put:
      operationId: update
      description: 記事を更新する
      tags:
        - Article
      parameters:
        - $ref: "#/components/parameters/ArticleId"
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Updated"
        400:
          description: 異常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailedUpdate"

    delete:
      operationId: delete
      description: 記事を削除する
      tags:
        - Article
      parameters:
        - $ref: "#/components/parameters/ArticleId"
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Deleted"
              example:
                articleId: 100
        400:
          description: 異常系
          content:
            application/json:
              schema:
                $ref:  "#/components/schemas/FailedDelete"
