openapi: 3.0.1
info:
  version: 1.0.0
  title: Article DomainのAPI
  description: Article関連のAPI週
  license:
    name: MIT
externalDocs:
  url: "https://himenon.github.io/openapi-practice/article"
  description: "自動生成ドキュメント"

servers:
  - url: http://localhost:4000
    description: ローカル開発環境
  - url: http://localhost:5000
    description: 本番環境

tags:
  - name: Article
    description: "投稿記事の情報"

components:
  schemas:
    Article:
      $ref: "./components/schemas/Article.yml"
    User:
      $ref: "./components/schemas/User.yml"
    Created:
      $ref: "./components/schemas/success/CreatedResponse.yml"
    Updated:
      $ref: "./components/schemas/success/UpdatedResponse.yml"
    Deleted:
      $ref: "./components/schemas/success/DeletedResponse.yml"
    FailedCreate:
      $ref: "./components/schemas/failed/CreateResponse.yml"
    FailedUpdate:
      $ref: "./components/schemas/failed/UpdateResponse.yml"
    FailedDelete:
      $ref: "./components/schemas/failed/DeleteResponse.yml"
  parameters:
    UserId:
      $ref: "./components/parameters/UserId.yml"
    ArticleId:
      $ref: "./components/parameters/ArticleId.yml"

paths:
  /article/:
    post:
      operationId: createArticle
      description: 記事を作成する
      tags:
        - Article
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Article"
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Created"

  /article/{articleId}:
    get:
      operationId: getArticle
      description: 記事を取得する
      tags:
        - Article
      parameters:
        - $ref: "#/components/parameters/ArticleId"
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        400:
          description: 異常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailedCreate"

    put:
      operationId: updateArticle
      description: 記事を更新する
      tags:
        - Article
      parameters:
        - $ref: "#/components/parameters/ArticleId"
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Updated"
        400:
          description: 異常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailedUpdate"

    delete:
      operationId: deleteArticle
      description: 記事を削除する
      tags:
        - Article
      parameters:
        - $ref: "#/components/parameters/ArticleId"
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Deleted"
              example:
                articleId: 100
        400:
          description: 異常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FailedDelete"

  /user/{userId}:
    get:
      operationId: getUser
      description: ユーザー情報を取得する
      tags:
        - User
      parameters:
        - $ref: "#/components/parameters/UserId"
      responses:
        200:
          description: "ユーザー情報を取得した"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
