openapi: 3.0.1
info:
  version: 1.0.0
  title: User DomainのAPI
  description: User関連のAPI週
  license:
    name: MIT
externalDocs:
  url: "https://himenon.github.io/openapi-practice/user"
  description: "自動生成ドキュメント"

servers:
  - url: http://localhost:4000
    description: ローカル開発環境
  - url: http://localhost:5000
    description: 本番環境

tags:
- name: User
  description: "投稿記事の情報"

components:
  schemas:
    Model:
      $ref: "./components/schemas/_Model.yml"
  parameters:
    UserId:
      $ref: ./components/parameters/UserId.yml

paths:
  /user/{userId}:
    get:
      operationId: get
      description: ユーザー情報を取得する
      tags:
        - User
      parameters:
        - $ref: "#/components/parameters/UserId"
      responses:
        200:
          description: "ユーザー情報を取得した"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Model"
